apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsrv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appsrv
  template:
    metadata:
      labels:
        app: appsrv
    spec:
      containers:
        - name: appsrv
          image: ghcr.io/caberger/leocloud-appsrv:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 1024Mi
              cpu: 1024m
      initContainers:
        - name: wait
          image: mysql:8
          command: ["sh", "-c", "/usr/local/bin/wait.sh"]
          volumeMounts:
            - name: init-script
              mountPath: /usr/local/bin
              readOnly: true
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: mysql-admin
                  key: username
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-admin
                  key: database
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-admin
                  key: password
      volumes:
        - name: init-script
          configMap:
            name: mysql-setup
            items:
              - key: wait.sh
                path: wait.sh
            defaultMode: 0744
---
apiVersion: v1
kind: Service
metadata:
  name: appsrv
spec:
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: appsrv
  selector:
    app: appsrv
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: student.cloud.htl-leonding.ac.at
      http:
        paths:
          - path: /c.aberger(/|$)(.*)$
            pathType: Prefix
            backend:
              service:
                name: nginx
                port:
                  number: 80

## backend ingress is unused, forwarded my nginx in default.conf
#---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: appsrv-ingress
#  annotations:
#    nginx.ingress.kubernetes.io/rewrite-target: /api/$1
#spec:
#  rules:
#    - host: student.cloud.htl-leonding.ac.at
#      http:
#        paths:
#          - path: /c.aberger/api/(.*)$
#            pathType: Prefix
#            backend:
#              service:
#                name: appsrv
#                port:
#                  number: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-setup
data:
  create.sql: |
    select "hello from database init script!" from dual;
  wait.sh: |
    until echo '\q' | mysql -hmysql -P"$PORT" -u"$USER" -p"$PASSWORD" $DATABASE; do
        echo "waiting for godot ..."
        sleep 2
    done
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-admin
type: kubernetes.io/basic-auth
stringData:
  username: user
  password: password
  database: db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 5Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mysql
  template:
    metadata:
      labels:
        component: mysql
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: database
        - name: init-script
          configMap:
            name: mysql-setup
            items:
              - key: create.sql
                path: create.sql
      containers:
        - name: mysql
          image: mysql:8
          resources:
            requests:
              memory: "500Mi"
              cpu: "200m"
            limits:
              memory: "1Gi"
              cpu: "400m"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
              readOnly: true
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-admin
                  key: username
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-admin
                  key: database
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-admin
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-admin
                  key: password
            - name: MYSQL_ROOT_HOST
              value: '%'
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
      name: mysql
  selector:
    component: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ghcr.io/caberger/leocloud-nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: BASE_HREF
              value: "c.aberger"
          resources:
                requests:
                  memory: "64Mi"
                  cpu: "250m"
                limits:
                  memory: "128Mi"
                  cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: nginx
